id: 6ef13074-1446-4de7-8e9e-d410739cca0d
name: ProjectContext
type: c4-project
caepVersion: 6
description: This is a sample project configuration for C4 model generation.
children:
- id: 2a034d75-1acc-4c8d-860f-5a09cb178f0e
  type: software-system
- id: c09e1cfe-da6a-4081-84d4-25bec9506810
  type: person
tenantId: 5f37364f-201e-47ea-2e89-08dd02619fda
